#!/data/data/com.termux/files/usr/bin/bash
unset LD_LIBRARY_PATH
unset LD_PRELOAD
PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
exec "$PREFIX/glibc/lib/ld-linux-aarch64.so.1" \
  --library-path "$PREFIX/glibc/lib" \
  "$PREFIX/glibc/bin/gcc-ranlib" "$@"
