#!/data/data/com.termux/files/usr/bin/bash
unset LD_PRELOAD
PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
export PATH="$PREFIX/glibc/bin:$PATH"
exec "$PREFIX/glibc/lib/ld-linux-aarch64.so.1" \
  --library-path "$PREFIX/glibc/lib:${LD_LIBRARY_PATH:-}" \
  "$@"
